'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/AuthProvider'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import {persistor, store} from "../redux/store"

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <AuthProvider>
        <Provider store={store}>
        <PersistGate persistor={persistor}>
        <Navbar />
       {children}
       <Footer />
        </PersistGate>
        </Provider>
        </AuthProvider>           
        </body>
    </html>
  )
}
